let traductor = {
    bucles: 'loop',
    for: 'por',
    lista: 'array',
    in: 'en',
    declaraction: 'declaracion',
    variable: 'variable',
    asignation: 'asignacion',
    value: 'valor',
    Object: 'objeto',
    function: 'funcion',
    return: 'devolver',
    if: 'si',
    else: 'sino',
    elseif: 'sino si',
    while: 'mientras',
    do: 'hacer',
    break: 'salir',
    continue: 'continuar',
    switch: 'cambiar',
    case: 'caso',
    default: 'por defecto',
    try: 'intentar',
    catch: 'capturar',
    finally: 'finalmente',
    throw: 'lanzar',
    debugger: 'depurar',
    alert: 'alerta',
    prompt: 'preguntar',
    confirm: 'confirmar',
    typeof: 'tipo de',
    instanceof: 'instancia de',
    undefined: 'indefinido',
    null: 'nulo',
    NaN: 'no numero',
    Infinity: 'infinito',
};
for (let i in traductor) {
    console.log(i + ': ' + traductor[i]);
};
