let numeros = 56;
let decimales = 5.1566; 
let negativos = -56;
let negativosDecimales = -5.1566;
let cero = 0;
let ceroDecimal = 0.0;
//let ceroComa = 0,0;
//let ceroComaDecimal = 0,0.0;
//let ceroComaDecimal2 = 0.0,0;
//let ceroComaDecimal3 = 0.0,0.0;
let infinito = Infinity;
let negativoInfinito = -Infinity;
let nan = NaN;
let negativoNan = -NaN;
console.log(numeros);
console.log(decimales);
console.log(negativos);
console.log(negativosDecimales);
console.log(cero);
console.log(ceroDecimal);
//console.log(ceroComa);
//console.log(ceroComaDecimal);
//console.log(ceroComaDecimal2);
//console.log(ceroComaDecimal3);
console.log(infinito);
console.log(negativoInfinito);
console.log(nan);
console.log(negativoNan);
//console.log(math.round(numeros));
//console.log(math.floor(numeros));
//console.log(math.ceil(numeros));
//console.log(math.trunc(numeros));
//console.log(math.random());
//console.log(math.random(numeros) * 10);
//console.log(math.abs(-10));
//console.log(math.pow(2, 3));
//console.log(math.sqrt(9));
//console.log(math.sin(90));
//console.log(math.cos(90));
//console.log(math.tan(90));
//console.log(math.asin(1));
//console.log(math.acos(1));
//console.log(math.atan(1));
//console.log(math.atan2(1, 1));
//console.log(math.exp(1));
//console.log(math.log(1));
//console.log(math.log10(1));
//console.log(math.log2(1));
//console.log(math.max(1, 2, 3, 4, 5));
//console.log(math.min(1, 2, 3, 4, 5));
//console.log(math.hypot(3, 4));
//console.log(math.imul(3, 4));
//console.log(math.fround(1));
//console.log(math.clz32(1));
//console.log(math.cbrt(1));
//console.log(math.sign(1));
//console.log(math.expm1(1));
//console.log(math.log1p(1));
//console.log(math.log10(1));
//console.log(math.log2(1));
//console.log(math.trunc(1));
//console.log(math.PI());
//console.log(math.E());
//console.log(math.LN2());
//console.log(math.LN10());
//console.log(math.LOG2E());
//console.log(math.LOG10E());
//console.log(math.SQRT1_2());
//console.log(math.SQRT2());
//console.log(math.abs(-10));
//console.log(math.acosh(1));
//console.log(math.asinh(1));
//console.log(math.atanh(1));
//console.log(math.cosh(1));
//console.log(math.sinh(1));
//console.log(math.tanh(1));
