let diez = 10;
let cinco = 5;
console.log(diez == cinco);
console.log(diez != cinco);
console.log(diez > cinco);
console.log(diez < cinco);
console.log(diez >= cinco);
console.log(diez <= cinco);
console.log(diez === cinco);
console.log(diez !== cinco);
